# This is a basic workflow to help you get started with Actions

name: Build website

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/setup-dotnet@v1
      name: Setup Dot Net 
      with:
        dotnet-version: '3.1.x'

    - name: Checkout 
      uses: actions/checkout@v3.0.2
      with:
        submodules: recursive
        lfs: true

    - run: dotnet run -- deploy
      name: Deploy Netlify
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_KEY: ${{ secrets.NETLIFY_DEPLOY_KEY }}      
